### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by paulvi** [jdillon/mvnsh#13]
How to use? 

give a link in README

**Comment by jdillon** [comment]
not quite sure what to say about this; the README.md has a simple example already; but its an interactive command shell, you run the shell; then there is a `mvn` command which essentially works the same way that the official apache-maven `bin/mvn` command works.

**Comment by paulvi** [comment]
README does not have example

There should be usage section,

perfect demo is like

![](https://raw.githubusercontent.com/juven/maven-bash-completion/master/demo.gif)
