### ISSUE TITLE
Add Roadmap

### ISSUE THREAD

**Issue by balazs-zsoldos** [jdillon/mvnsh#15]
There is some activity on the project again. It would be really nice to see a roadmap in the wiki or a blog post.

**Comment by jdillon** [comment]
sorry no roadmap per-se; i basically hack on this when I have time and recently have had time and motivation to update mvnsh and gshell.

atm the plan is to mostly to update gshell to modernize and simplify, consume updates to core dependencies (like jline3 which was a non-trivial change), and then likely shore up testing.  GShell likely has more pending todos, but mostly trying to remove the gross hacks and simply.
