### ISSUE TITLE
dependency error. mvnsh 1.1

### ISSUE THREAD

**Issue by dmrzh** [jdillon/mvnsh#16]
Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/p2/bridge/p2-runtime/1.0.7/p2-runtime-1.0.7.zip (5073 KB at 951.5 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Maven Shell ........................................ SUCCESS [ 18.876 s]
[INFO] Maven Shell Commands ............................... SUCCESS [  5.982 s]
[INFO] Maven Shell Commands :: Maven ...................... FAILURE [01:13 min]
[INFO] Maven Shell Commands :: Archetype .................. SKIPPED
[INFO] Maven Shell Commands :: Nexus ...................... SKIPPED
[INFO] Maven Shell :: Bootstrap ........................... SKIPPED
[INFO] Maven Shell :: Personality ......................... SKIPPED
[INFO] Maven Shell Dist ................................... SKIPPED
[INFO] Maven Shell Dist :: Maven Extensions ............... SKIPPED
[INFO] Maven Shell Dist :: Assembly ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:52 min
[INFO] Finished at: 2016-06-09T13:19:13+03:00
[INFO] Final Memory: 27M/239M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonatype.maven.plugins:maven-sisu-assembler-plugin:1.0.7:generate (default) on project mvnsh-maven: Execution default of goal org.sonatype.maven.plugins:maven-sisu-assembler-plugin:1.0.7:generate failed: Plugin org.sonatype.maven.plugins:maven-sisu-assembler-plugin:1.0.7 or one of its dependencies could not be resolved: Could not find artifact org.eclipse:org.eclipse.osgi:jar:3.7.0.v20100910 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :mvnsh-maven

**Comment by jdillon** [comment]
this is pretty old; closing; mvnsh (and gshell) no longer use that maven-sisu-assembler-plugin.
