### ISSUE TITLE
Mystery ExceptionInInitializerError with cd command

### ISSUE THREAD

**Issue by garydgregory** [jdillon/mvnsh#21]
mvnsh(/):mvnsh> cd \vcs
java.lang.ExceptionInInitializerError

On Windows.
 
Then:
mvnsh(/):mvnsh> cd /vcs
java.lang.NoClassDefFoundError: Could not initialize class com.planet57.gshell.util.io.FileAssert$Messages

I have a "C:\vcs" folder 

This works OK:

mvnsh(/):mvnsh> cd c:\vcs

**Comment by jdillon** [comment]
this is a left over IIUC from the massive refactoring and cleanup that is on going and should no longer be a problem in the latest snapshot.

**Comment by garydgregory** [comment]
Still no go with the latest pull:

```mvnsh(C:\vcs\git\github\jdillon\mvnsh)> cd /vcs
com.planet57.gshell.util.io.FileAssert$AssertionException: File not found: C:\vcs\git\github\jdillon\mvnsh\vcs
mvnsh(C:\vcs\git\github\jdillon\mvnsh)> cd \vcs
com.planet57.gshell.util.io.FileAssert$AssertionException: File not found: C:\vcs\git\github\jdillon\mvnsh\vcs
mvnsh(C:\vcs\git\github\jdillon\mvnsh)>```

**Comment by garydgregory** [comment]
Also no go on Windows with:
```
mvnsh(C:\vcs\git\github\jdillon\mvnsh)> cd c:\vcs
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
```

**Comment by jdillon** [comment]
well thats a different failure; there is some special muck for windows but I haven't tested if its functional yet;  defs need to spin up windows vm and see what might be unhappy.
