### ISSUE TITLE
shell prompt uses wrong path

### ISSUE THREAD

**Issue by garydgregory** [jdillon/mvnsh#22]
pwd shows me a different path than where the program thinks I am:

mvnsh(/):mvnsh> pwd
C:\vcs\git\github\jdillon\mvnsh

I am expecting:

mvnsh(C:\vcs\git\github\jdillon\mvnsh):mvnsh> 

Or something like that.

**Comment by jdillon** [comment]
do you mean the `mvnsh(/)` part of that?  the default atm is:

```
shell.prompt='@|bold mvnsh|@(${shell.group}):${shell.user.dir~.}> '
```

which is the command group in `()` followed by a reference to the current directory shorted to the last path element.

You can change this if you like if you want the full path and omit the shell.group, for example:

```
set shell.prompt '@|bold mvnsh|@(${shell.user.dir})> '
```

**Comment by garydgregory** [comment]
OK, that works on in the shell. Thank you. How can I make that the default? (I think it should be the default of course ;-)

**Comment by mosabua** [comment]
I think it should NOT be the default. Its too long. Unless you have the prompt and then insert a line break so you actually type below the prompt.

**Comment by jdillon** [comment]
the default prompt will probably change to be simplified, but if you want you can edit: $HOME/.m2/mvnsh.rc and run:

```
set shell.prompt '@|bold mvnsh|@(${shell.user.dir})> '
```

though you are on windows so caveat is that I've not verified that the setup of that works properly (yet).
