### ISSUE TITLE
mvnsh tries to compile the project using java 1.3

### ISSUE THREAD

**Issue by drieselliott** [jdillon/mvnsh#4]
When I run mvn clean install using my standard installation of maven everything works fine. As soon as I use the command in mvnsh, it throws an error telling me that annotations are not supported when compiling against java version 1.3.

**Comment by vijayanettem** [comment]
Was this issue resolved? I am running into exact same issue while compiling a flume plugin. Could you please help?

**Comment by gregmazur** [comment]
Solved now? have the same issue.

**Comment by charlesrochati** [comment]
have any of you solved this problem?

**Comment by gregmazur** [comment]
```check all of the settings, also try add to pom.xml 
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
    </properties>```

**Comment by charlesrochati** [comment]
thanks, fixed

**Comment by jdillon** [comment]
appears to have been a user configuration error, not setting the compiler configuration in poms
