### ISSUE TITLE
Can not compile on Maven 3.1.1

### ISSUE THREAD

**Issue by vit1251** [jdillon/mvnsh#8]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Maven Shell ....................................... SUCCESS [22.121s]
[INFO] Maven Shell Commands .............................. SUCCESS [10.385s]
[INFO] Maven Shell Commands :: Maven ..................... FAILURE [45.871s]
[INFO] Maven Shell Commands :: Archetype ................. SKIPPED
[INFO] Maven Shell Commands :: Nexus ..................... SKIPPED
[INFO] Maven Shell :: Bootstrap .......................... SKIPPED
[INFO] Maven Shell :: Personality ........................ SKIPPED
[INFO] Maven Shell Dist .................................. SKIPPED
[INFO] Maven Shell Dist :: Maven Extensions .............. SKIPPED
[INFO] Maven Shell Dist :: Assembly ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:35.807s
[INFO] Finished at: Thu Mar 12 21:41:02 MSK 2015
[INFO] Final Memory: 19M/65M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonatype.maven.plugins:maven-sisu-assembler-plugin:1.0.7:generate (default) on project mvnsh-maven: Execution default of goal org.sonatype.maven.plugins:maven-sisu-assembler-plug
in:1.0.7:generate failed: Plugin org.sonatype.maven.plugins:maven-sisu-assembler-plugin:1.0.7 or one of its dependencies could not be resolved: Could not find artifact org.eclipse:org.eclipse.osgi:jar:3.7.0.v20100
910 in central (http://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by jdillon** [comment]
ugh I forgot all about the evil sisu-assembler poops :-\

**Comment by jdillon** [comment]
https://github.com/jdillon/mvnsh/pull/9 should be buildable with latest maven 3.3.3

**Comment by jdillon** [comment]
master should be buildable with modern maven now.
